apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '17'
  creationTimestamp: '2020-05-05T17:02:18Z'
  generation: 19
  labels:
    name: tomcat
    tier: dev
  name: nginx
  namespace: myproject
  resourceVersion: '3012163'
  selfLink: /apis/apps/v1/namespaces/myproject/deployments/nginx
  uid: 2dc25767-8ef2-11ea-a323-eefa1412113f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: tomcat
      tier: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: tomcat
        tier: dev
    spec:
      containers:
        - image: 'nginx:1.18'
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 8085
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/
              name: conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      serviceAccount: useroot
      serviceAccountName: useroot
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: nginx
          name: conf
